name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.2.3
  - scikit-learn=1.0.2
  - matplotlib=3.3.4
  - pip
  - pip:
      - mlflow==1.29.0
      - wandb==0.13.9
